version: '3.8'

services:
  db:
    image: postgres:13
    container_name: defensys_db
    environment:
      - POSTGRES_USER=defensys_user
      - POSTGRES_PASSWORD=defensys_password
      - POSTGRES_DB=defensys_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - defensys_net

  api:
    build: ./backend
    container_name: defensys_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - defensys_net

volumes:
  postgres_data:

networks:
  defensys_net:
    driver: bridge
